twig:
    default_path: '%kernel.project_dir%/templates'

    globals:    
        batman: "Batman"
        gproducts: '@App\Globals\Products'
        gbrands: '@App\Globals\Brands'
        gtypes: '@App\Globals\Types'
        
when@test:
    twig:
        strict_variables: true
